// Generated by gencpp from file software_training_assignment/MoveResult.msg
// DO NOT EDIT!


#ifndef SOFTWARE_TRAINING_ASSIGNMENT_MESSAGE_MOVERESULT_H
#define SOFTWARE_TRAINING_ASSIGNMENT_MESSAGE_MOVERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace software_training_assignment
{
template <class ContainerAllocator>
struct MoveResult_
{
  typedef MoveResult_<ContainerAllocator> Type;

  MoveResult_()
    : time()  {
    }
  MoveResult_(const ContainerAllocator& _alloc)
    : time()  {
  (void)_alloc;
    }



   typedef ros::Duration _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::software_training_assignment::MoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::software_training_assignment::MoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct MoveResult_

typedef ::software_training_assignment::MoveResult_<std::allocator<void> > MoveResult;

typedef boost::shared_ptr< ::software_training_assignment::MoveResult > MoveResultPtr;
typedef boost::shared_ptr< ::software_training_assignment::MoveResult const> MoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::software_training_assignment::MoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::software_training_assignment::MoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::software_training_assignment::MoveResult_<ContainerAllocator1> & lhs, const ::software_training_assignment::MoveResult_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::software_training_assignment::MoveResult_<ContainerAllocator1> & lhs, const ::software_training_assignment::MoveResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace software_training_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::software_training_assignment::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::software_training_assignment::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::software_training_assignment::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::software_training_assignment::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::software_training_assignment::MoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::software_training_assignment::MoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::software_training_assignment::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "984d9fd14be9281d38a42fa7ba891c27";
  }

  static const char* value(const ::software_training_assignment::MoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x984d9fd14be9281dULL;
  static const uint64_t static_value2 = 0x38a42fa7ba891c27ULL;
};

template<class ContainerAllocator>
struct DataType< ::software_training_assignment::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "software_training_assignment/MoveResult";
  }

  static const char* value(const ::software_training_assignment::MoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::software_training_assignment::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"duration time\n"
;
  }

  static const char* value(const ::software_training_assignment::MoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::software_training_assignment::MoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::software_training_assignment::MoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::software_training_assignment::MoveResult_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOFTWARE_TRAINING_ASSIGNMENT_MESSAGE_MOVERESULT_H
