// Generated by gencpp from file software_training_assignment/resetMovingTurtleResponse.msg
// DO NOT EDIT!


#ifndef SOFTWARE_TRAINING_ASSIGNMENT_MESSAGE_RESETMOVINGTURTLERESPONSE_H
#define SOFTWARE_TRAINING_ASSIGNMENT_MESSAGE_RESETMOVINGTURTLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace software_training_assignment
{
template <class ContainerAllocator>
struct resetMovingTurtleResponse_
{
  typedef resetMovingTurtleResponse_<ContainerAllocator> Type;

  resetMovingTurtleResponse_()
    {
    }
  resetMovingTurtleResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct resetMovingTurtleResponse_

typedef ::software_training_assignment::resetMovingTurtleResponse_<std::allocator<void> > resetMovingTurtleResponse;

typedef boost::shared_ptr< ::software_training_assignment::resetMovingTurtleResponse > resetMovingTurtleResponsePtr;
typedef boost::shared_ptr< ::software_training_assignment::resetMovingTurtleResponse const> resetMovingTurtleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace software_training_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "software_training_assignment/resetMovingTurtleResponse";
  }

  static const char* value(const ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct resetMovingTurtleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::software_training_assignment::resetMovingTurtleResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SOFTWARE_TRAINING_ASSIGNMENT_MESSAGE_RESETMOVINGTURTLERESPONSE_H
