// Generated by gencpp from file software_training_assignment/resetMovingTurtle.msg
// DO NOT EDIT!


#ifndef SOFTWARE_TRAINING_ASSIGNMENT_MESSAGE_RESETMOVINGTURTLE_H
#define SOFTWARE_TRAINING_ASSIGNMENT_MESSAGE_RESETMOVINGTURTLE_H

#include <ros/service_traits.h>


#include <software_training_assignment/resetMovingTurtleRequest.h>
#include <software_training_assignment/resetMovingTurtleResponse.h>


namespace software_training_assignment
{

struct resetMovingTurtle
{

typedef resetMovingTurtleRequest Request;
typedef resetMovingTurtleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct resetMovingTurtle
} // namespace software_training_assignment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::software_training_assignment::resetMovingTurtle > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::software_training_assignment::resetMovingTurtle&) { return value(); }
};

template<>
struct DataType< ::software_training_assignment::resetMovingTurtle > {
  static const char* value()
  {
    return "software_training_assignment/resetMovingTurtle";
  }

  static const char* value(const ::software_training_assignment::resetMovingTurtle&) { return value(); }
};


// service_traits::MD5Sum< ::software_training_assignment::resetMovingTurtleRequest> should match
// service_traits::MD5Sum< ::software_training_assignment::resetMovingTurtle >
template<>
struct MD5Sum< ::software_training_assignment::resetMovingTurtleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::software_training_assignment::resetMovingTurtle >::value();
  }
  static const char* value(const ::software_training_assignment::resetMovingTurtleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::software_training_assignment::resetMovingTurtleRequest> should match
// service_traits::DataType< ::software_training_assignment::resetMovingTurtle >
template<>
struct DataType< ::software_training_assignment::resetMovingTurtleRequest>
{
  static const char* value()
  {
    return DataType< ::software_training_assignment::resetMovingTurtle >::value();
  }
  static const char* value(const ::software_training_assignment::resetMovingTurtleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::software_training_assignment::resetMovingTurtleResponse> should match
// service_traits::MD5Sum< ::software_training_assignment::resetMovingTurtle >
template<>
struct MD5Sum< ::software_training_assignment::resetMovingTurtleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::software_training_assignment::resetMovingTurtle >::value();
  }
  static const char* value(const ::software_training_assignment::resetMovingTurtleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::software_training_assignment::resetMovingTurtleResponse> should match
// service_traits::DataType< ::software_training_assignment::resetMovingTurtle >
template<>
struct DataType< ::software_training_assignment::resetMovingTurtleResponse>
{
  static const char* value()
  {
    return DataType< ::software_training_assignment::resetMovingTurtle >::value();
  }
  static const char* value(const ::software_training_assignment::resetMovingTurtleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SOFTWARE_TRAINING_ASSIGNMENT_MESSAGE_RESETMOVINGTURTLE_H
