// Auto-generated. Do not edit!

// (in-package software_training_assignment.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MoveGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.absolutePos = null;
    }
    else {
      if (initObj.hasOwnProperty('absolutePos')) {
        this.absolutePos = initObj.absolutePos
      }
      else {
        this.absolutePos = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveGoal
    // Serialize message field [absolutePos]
    bufferOffset = _arraySerializer.float32(obj.absolutePos, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveGoal
    let len;
    let data = new MoveGoal(null);
    // Deserialize message field [absolutePos]
    data.absolutePos = _arrayDeserializer.float32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.absolutePos.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'software_training_assignment/MoveGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a38e046c785f40d93c6a1dd61ea8c2b5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float32[] absolutePos
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveGoal(null);
    if (msg.absolutePos !== undefined) {
      resolved.absolutePos = msg.absolutePos;
    }
    else {
      resolved.absolutePos = []
    }

    return resolved;
    }
};

module.exports = MoveGoal;
